"""Remove unique constraint from auth id

Revision ID: 92182602e517
Revises: aba27aa52636
Create Date: 2026-02-06 15:02:12.030758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92182602e517'
down_revision: Union[str, Sequence[str], None] = 'aba27aa52636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_auth_user_id_key'), 'tasks', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('tasks_auth_user_id_key'), 'tasks', ['auth_user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
